'use strict';
let experienceHome=home;
let activeRoom='all',mode='quiz',activeQuiz=null,quizAnswers=new Map();
const esc=v=>String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function roomFor(q){return quizRooms.find(r=>r.id===q.room)}
function visitedRoom(id){return quizzes.filter(q=>q.room===id&&quizAnswers.has(q.id)).length}
function passCount(){return quizAnswers.size+completed.size}
updatePass=function(){$('#passport b').textContent=`${passCount()} / 130`};
function getQuizList(){return activeRoom==='all'?Array.from({length:25},(_,i)=>quizRooms.map(r=>quizzes.filter(q=>q.room===r.id)[i])).flat():quizzes.filter(q=>q.room===activeRoom)}
home=function(){
 clearTimers();current=-1;activeQuiz=null;
 if(mode==='experience'){experienceHome();const h=document.createElement('div');h.innerHTML=modeButtons();main.prepend(h);updatePass();return}
 const list=getQuizList(),r=quizRooms.find(r=>r.id===activeRoom);
 main.innerHTML=`<section class="quiz-intro enter"><div><div class="eyebrow">A LITTLE QUESTION. A BIG DISCOVERY.</div><h1>心のふしぎを、<br><em>ひとつ、ひとつ。</em></h1></div><div class="welcome-note"><span class="welcome-spark" aria-hidden="true">✳</span><p>好きな部屋で、好きな問いを。<br>実験の結末を予想して、<br>「へえ！」を持ち帰ろう。</p></div></section>${modeButtons()}<nav class="room-picker" aria-label="心理学の部屋を選ぶ"><button class="room-pick all ${activeRoom==='all'?'selected':''}" aria-pressed="${activeRoom==='all'}" data-category="all"><span class="room-symbol">＋</span><strong>すべての部屋</strong><small>100 CARDS</small></button>${quizRooms.map(r=>`<button class="room-pick ${activeRoom===r.id?'selected':''}" style="--room-color:${r.color}" aria-pressed="${activeRoom===r.id}" data-category="${r.id}"><span class="room-symbol" aria-hidden="true">${r.symbol}</span><strong>${r.name}</strong><small>${visitedRoom(r.id)} / 25 発見</small></button>`).join('')}</nav><div class="quiz-section-title"><div><span class="eyebrow">${r?r.en:'PICK YOUR CURIOSITY'}</span><h2>${r?r.intro:'どの実験から、のぞいてみる？'}</h2></div><span class="free-tag">どのカードも、いつでも挑戦できます</span></div><section class="quiz-grid" aria-label="実験クイズカード">${list.map((q,i)=>quizTile(q,i)).join('')}</section><div class="quiz-bottom-note"><b>✓ 正解でも、間違えても、発見はひとつ。</b><p>全カードを最初から自由に選べます。解説を読んで、好きなところへ。<br>出題は研究をもとに再構成した学習クイズです。各解説で研究の条件と出典を確認できます。</p></div>`;
 updatePass();window.scrollTo(0,0)
};
function modeButtons(){return `<div class="mode-switch" aria-label="展示の種類"><button data-mode="quiz" aria-pressed="${mode==='quiz'}" class="${mode==='quiz'?'selected':''}">実験クイズ <b>100</b></button><button data-mode="experience" aria-pressed="${mode==='experience'}" class="${mode==='experience'?'selected':''}">触って体験 <b>30</b></button></div>`}
function quizTile(q,i){const r=roomFor(q),done=quizAnswers.has(q.id);return `<button class="quiz-tile enter" style="--room-color:${r.color};animation-delay:${Math.min(i,7)*.035}s" data-quiz="${q.id}"><div class="quiz-tile-top"><span>${r.name}</span><span>${done?'✓ 発見済み':q.kind}</span></div><div class="quiz-art" aria-hidden="true"><span class="big-q">Q<span>?</span></span><span class="study-year">STUDY<br><b>${q.year}</b></span></div><div class="quiz-tile-body"><h3>${q.title}</h3><p>${q.teaser}</p><div class="quiz-tile-bottom"><span>約1分 / ${q.options.length}択</span><span class="quiz-open">${done?'もう一度':'挑戦する'} ↗</span></div></div></button>`}
function openQuiz(id){const q=quizzes.find(x=>x.id===id);if(!q)return;clearTimers();current=-1;activeQuiz=q.id;renderQuiz();window.scrollTo(0,0)}
function renderQuiz(selected=null){const q=quizzes.find(x=>x.id===activeQuiz),r=roomFor(q),answered=selected!==null;
 main.innerHTML=`<div class="quiz-navigation"><button class="back" data-quizaction="map">← カードを選ぶ</button><span>${r.symbol} ${r.name}</span><button class="back" data-quizaction="another">別の実験へ ↗</button></div><div class="experiment-layout enter" style="--room-color:${r.color}"><article class="story-card"><div class="story-top"><span>EXPERIMENT FILE</span><span>${q.year}</span></div><div class="story-title"><span class="story-q" aria-hidden="true">Q.</span><div><span class="tag">${q.kind}</span><h1>${q.title}</h1></div></div><div class="story-scene"><span class="eyebrow">研究の場面・考えてみよう</span><p>${q.scene}</p></div><div class="story-aside"><span aria-hidden="true">✳</span><p>あなたなら、どう予想する？<br>知らなくても、直感でどうぞ。</p></div><div class="story-bottom">MIND PARK <span>正解より、発見を。</span></div></article><section class="question-card" aria-label="クイズに回答"><span class="eyebrow">${answered?'THE REVEAL':'MAKE YOUR GUESS'}</span><h2 id="question-title">${q.question}</h2><div class="quiz-options" role="group" aria-labelledby="question-title">${q.options.map((o,i)=>`<button data-answer="${i}" class="quiz-option ${answered?(i===q.answer?'correct':i===selected?'picked':'muted'):''}" ${answered?'disabled':''}><b>${String.fromCharCode(65+i)}</b><span>${o}</span>${answered&&i===q.answer?'<small>✓ 正解</small>':answered&&i===selected?'<small>あなたの予想</small>':''}</button>`).join('')}</div>${answered?answerPanel(q,selected):'<p class="answer-hint">答えをタップすると、結果と解説が開きます。<br>制限時間はありません。じっくり考えてもOK。</p>'}</section></div>`;
 if(answered){const result=$('#quiz-result');result.focus({preventScroll:true});result.scrollIntoView({behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'instant':'smooth',block:'nearest'})}
}
function answerPanel(q,selected){const right=selected===q.answer;return `<div id="quiz-result" tabindex="-1" class="quiz-result" aria-live="polite"><div class="discovery-label"><span>${right?'✳ 正解！ 発見をひとつ。':'✳ なるほど、そうなるんだ。'}</span><b>DISCOVERED</b></div><div class="term-label">${q.term}</div><h3>${q.headline}</h3>${q.stat?`<div class="study-chart" aria-label="本人の予想46%、実際の正答23%">${q.stat.map(([name,v])=>`<div class="bar-row"><span>${name}</span><div class="bar"><i style="width:${v}%"></i></div><b>${v}%</b></div>`).join('')}<small>研究1の平均割合</small></div>`:''}<p>${q.explain}</p><div class="takeaway"><span>POCKET NOTE / 日常に持ち帰ろう</span><p>${q.tip}</p></div><details class="research-note"><summary>実験の条件と出典を読む</summary><p>${q.limit}</p><a href="${esc(q.url)}" target="_blank" rel="noopener">${esc(q.source)} ↗</a><p class="source">場面は原研究をもとに日本語で要約しています。日常の例は学習用の応用です。</p></details><div class="quiz-result-actions"><button class="primary" data-quizaction="map">好きなカードを選ぶ ↗</button><button class="secondary" data-quizaction="another">別の実験に挑戦</button><button class="retry-text" data-quizaction="retry">この問題をもう一度</button></div></div>`}
function answerQuiz(index){const q=quizzes.find(x=>x.id===activeQuiz);if(!q||!Number.isInteger(index)||index<0||index>=q.options.length||$('#quiz-result'))return;quizAnswers.set(q.id,index);updatePass();renderQuiz(index)}
function anotherQuiz(){let candidates=quizzes.filter(q=>q.id!==activeQuiz&&(activeRoom==='all'||q.room===activeRoom));if(!candidates.length)candidates=quizzes.filter(q=>q.id!==activeQuiz);const unseen=candidates.filter(q=>!quizAnswers.has(q.id));const pool=unseen.length?unseen:candidates;openQuiz(pool[Math.floor(Math.random()*pool.length)].id)}
showPass=function(){$('#modalbody').innerHTML=`<div class="eyebrow">YOUR DISCOVERY PASS</div><h2>今日の「へえ！」、${passCount()}個。</h2><p>答えを知ったクイズも、触って試した展示も。<br>正解・不正解に関係なく、発見が集まります。</p><div class="discovery-rooms">${quizRooms.map(r=>`<div style="--room-color:${r.color}"><span>${r.symbol}</span><strong>${r.name}</strong><b>${visitedRoom(r.id)} / 25</b></div>`).join('')}<div style="--room-color:#ffadca"><span>↔</span><strong>触って体験</strong><b>${completed.size} / 30</b></div></div><p>${passCount()===130?'すべての展示を探検しました！ 気になった実験を、誰かに話してみよう。':'次はどんな問いに出会えるかな。どの部屋にも自由に入れます。'}</p><p class="source">発見の記録は、このページを開いている間だけ保存されます。再読み込みでリセットされます。</p>`;$('#modal').showModal()};
$('#passport').onclick=showPass;
$('#about').onclick=()=>{$('#modalbody').innerHTML='<div class="eyebrow">ABOUT MIND PARK</div><h2>心のふしぎを、自由に探検。</h2><p>100の心理学クイズと、30の体験展示。好きなカードから挑戦でき、正解でも不正解でも解説を読めます。体験展示のヒントと仕組みは、自分のタイミングで開けます。解放条件やライフ制限はありません。</p><p>実験結果・用語・日常への応用を、研究をもとに出題しています。古典研究の数字はその条件で得られた値です。各解説の「実験の条件と出典」も一緒にお楽しみください。</p><p>心理・性格・能力の診断ではありません。回答は外部へ送信せずページ内で処理し、再読み込みでリセットします。</p><button class="secondary" id="motion">演出を控えめに切り替える</button>';$('#modal').showModal();$('#motion').onclick=()=>{document.body.classList.toggle('reduced');$('#motion').textContent=document.body.classList.contains('reduced')?'通常の演出に戻す':'演出を控えめに切り替える'}};
document.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;if(b.dataset.mode){mode=b.dataset.mode;home()}else if(b.dataset.category){activeRoom=b.dataset.category;const y=window.scrollY;home();window.scrollTo(0,y)}else if(b.dataset.quiz){openQuiz(b.dataset.quiz)}else if(b.hasAttribute('data-answer')){answerQuiz(Number(b.dataset.answer))}else if(b.dataset.quizaction){const a=b.dataset.quizaction;if(a==='map'){mode='quiz';home()}else if(a==='another')anotherQuiz();else if(a==='retry'){renderQuiz();window.scrollTo(0,0)}}});
home();
